# Playbook: Create test containers in swarm overlay network
#
# See examples: https://docs.ansible.com/ansible/latest/modules/docker_swarm_module.html#examples
#
#
- hosts: all
  become: true
  vars:
    # create_containers: 4
    # default_container_name: docker
    # default_container_image: ubuntu
    # default_container_command: sleep 1d

  tasks:

    - name: Create test container in teonet
      command: docker service create --constraint 'node.hostname == teonet'   --network teo-overlay --name ubuntu-overlay-01 --hostname ubuntu-overlay-01 -t ubuntu

    - name: Create test container in dev-ks-2
      command: docker service create --constraint 'node.hostname == dev-ks-2' --network teo-overlay --name ubuntu-overlay-02 --hostname ubuntu-overlay-02 -t ubuntu

    - name: Create test container in dev-ks-3
      command: docker service create --constraint 'node.hostname == dev-ks-3' --network teo-overlay --name ubuntu-overlay-03 --hostname ubuntu-overlay-03 -t ubuntu

    # - name: Remove containers when test finished
    # commnad: docker service rm ubuntu-overlay-01 ubuntu-overlay-02 ubuntu-overlay-03
