# Playbook: teonet grafana service create on teonet node

- hosts: teonet
  become: true
  vars:
    image_grafana: grafana/grafana
    service_name: grafana
    #conf_host_path: /tmp/prometheus.yml

  tasks:

    - name: Remove running service
      shell: docker service rm {{service_name}}
      failed_when: False

    - name: Update docker image
      shell: docker pull {{image_grafana}}

    - name: Run (or update) grafana on teonet node
      shell: > 
        docker service create 
        --name grafana 
        --replicas 1 
        --constraint 'node.hostname == teonet'
        --publish published=3000,target=3000,protocol=tcp
        {{image_grafana}}

    - name: Copy dashboard config file
      copy:
        src: files/1-node-explorer.json
        dest: /tmp/1-node-explorer.json

    # - name: Import Grafana Node exporter dashboard
    #   grafana_dashboard:
    #     grafana_url: http://grafana.company.com
    #     state: present
    #     message: Updated by ansible
    #     overwrite: yes
    #     path: /tmp/1-node-explorer.json
