# Playbook: Install node exporte
#
# Install and build on host where you run ansibe:
# 
#   go get github.com/prometheus/node_exporter
#   cd ${GOPATH-$HOME/go}/src/github.com/prometheus/node_exporter
#   make
#   ./node_exporter <flags>
#
# On error "DecodeRune not declared..." run next command and than reinstall 
# node exporte:
#
#   rm -rf ${GOPATH-$HOME/go}/src/github.com/golangci/golangci-lint
#   GO111MODULE=off go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
#
# Some additional info:
#
#   https://www.scaleway.com/en/docs/configure-prometheus-monitoring-with-grafana/
#
#
- hosts: all
  become: true
  vars:
    # create_containers: 4
    # default_container_name: docker
    # default_container_image: ubuntu
    # default_container_command: sleep 1d

  tasks:

    - name: Stop Node Exporter service
      command: sudo systemctl stop node_exporter
      failed_when: False

    - name: Create a user for Node Exporter without the possibility to log in
      command: sudo useradd --no-create-home --shell /bin/false node_exporter
      failed_when: False

    - name: Setup node_exporter
      copy:
        src: "{{ lookup('env','HOME') }}/go/src/github.com/prometheus/node_exporter/node_exporter"
        dest: /usr/local/bin/node_exporter
        mode: '0755'

    - name: Copy linux service config file
      copy:
        src: files/node_exporter.service
        dest: /etc/systemd/system/node_exporter.service

    - name: Reload Systemd to use the newly defined service
      command: sudo systemctl daemon-reload

    - name: Run Node Exporter service
      command: sudo systemctl start node_exporter

    - name: Get Node Exporter status
      command: sudo systemctl status node_exporter
      register: system_print

    - name: debug print
      debug: var=system_print.stdout_lines